#!/bin/sh
# This file runs when you startx

# Run programs
set_bg &			# set background in set_bg script (on path)
xset r rate 200 50 &		# speed up repeated key delay
picom &				# compositor for transparency
# slstatus &			# status bar
unclutter &			# hide cursor while idle
alert_power_mode_change &	# monitor power mode
redshift-gtk &			# screen colour temperature
dunst &				# notification server

# Pulse/Chromium-based browser bug fix
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

# Backlight
light -S 100 # set monitor backlight to 100%
light -Srs "sysfs/leds/asus::kbd_backlight" 3 # set keyboard backlight to 100%
